In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout

In [3]:
train_data = pd.read_csv('Google_Stock_Price_Train.csv', date_parser = True)
train_data.head()

Date    Open    High     Low   Close    Volume
0  2012-01-03  325.25  332.83  324.97  663.59   7380500
1  2012-01-04  331.27  333.87  329.08  666.45   5749400
2  2012-01-05  329.83  330.75  326.89  657.21   6590300
3  2012-01-06  328.34  328.77  323.68  648.24   5405900
4  2012-01-09  322.04  322.29  309.46  620.76  11688800

In [4]:
test_data = pd.read_csv('Google_Stock_Price_Test.csv', date_parser = True)
test_data.head()

Date    Open    High     Low   Close   Volume
0  2017-01-03  778.81  789.63  775.80  786.14  1657300
1  2017-01-04  788.36  791.34  783.16  786.90  1073000
2  2017-01-05  786.08  794.48  785.02  794.02  1335200
3  2017-01-06  795.26  807.90  792.20  806.15  1640200
4  2017-01-09  806.40  809.97  802.83  806.65  1272400

In [5]:
train_data = train_data.drop(['Date', 'Close'], axis = 1)
train_data.head()

Open    High     Low    Volume
0  325.25  332.83  324.97   7380500
1  331.27  333.87  329.08   5749400
2  329.83  330.75  326.89   6590300
3  328.34  328.77  323.68   5405900
4  322.04  322.29  309.46  11688800

In [109]:
scaler = MinMaxScaler()
train_data = scaler.fit_transform(train_data)

train_data

array([[0.08581368, 0.09640129, 0.09044931, 0.29525831],
       [0.09701243, 0.09834351, 0.09823458, 0.22993592],
       [0.09433366, 0.09251685, 0.09408623, 0.26361233],
       ...,
       [0.95725128, 0.95807422, 0.95844067, 0.04589107],
       [0.93796041, 0.94257381, 0.95033338, 0.02949139],
       [0.93688146, 0.93669113, 0.93421352, 0.07056868]])

In [110]:
X_train=[]
y_train = []
n=3

for i in range(n,len(train_data)):
    X_train.append(train_data[i-n: i])
    y_train.append(train_data[i,0])


In [115]:
X_train[0]


array([[0.08581368, 0.09640129, 0.09044931, 0.29525831],
       [0.09701243, 0.09834351, 0.09823458, 0.22993592],
       [0.09433366, 0.09251685, 0.09408623, 0.26361233]])

In [116]:
X_train, y_train = np.array(X_train), np.array(y_train)

In [117]:
X_train.shape, y_train.shape

((1255, 3, 4), (1255,))

# LSTM MODEL

In [124]:
reg = Sequential()
####NOT WORKING SOMETHINGS WRONG HERE 
reg.add(LSTM(units = 50, input_shape=(X_train.shape[0], 4)))
reg.add(Dropout(0.2))

# reg.add(LSTM(units=60, activation = 'relu', return_sequences=True))
# reg.add(Dropout(0.3))

# reg.add(LSTM(units=80, activation = 'relu', return_sequences=True))
# reg.add(Dropout(0.4))


# reg.add(LSTM(units=120, activation = 'relu', return_sequences=True))
# reg.add(Dropout(0.5))


reg.add(Dense(units = 1))






             

In [125]:
reg.summary()
X_train


Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_15 (LSTM)               (None, 50)                11000     
_________________________________________________________________
dropout_9 (Dropout)          (None, 50)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 51        
Total params: 11,051
Trainable params: 11,051
Non-trainable params: 0
_________________________________________________________________


array([[[0.08581368, 0.09640129, 0.09044931, 0.29525831],
        [0.09701243, 0.09834351, 0.09823458, 0.22993592],
        [0.09433366, 0.09251685, 0.09408623, 0.26361233]],

       [[0.09701243, 0.09834351, 0.09823458, 0.22993592],
        [0.09433366, 0.09251685, 0.09408623, 0.26361233],
        [0.09156187, 0.08881917, 0.08800576, 0.21617942]],

       [[0.09433366, 0.09251685, 0.09408623, 0.26361233],
        [0.09156187, 0.08881917, 0.08800576, 0.21617942],
        [0.07984225, 0.07671765, 0.06106986, 0.46779736]],

       ...,

       [[0.95475854, 0.95637477, 0.96863161, 0.03861834],
        [0.95204256, 0.95529161, 0.96616912, 0.02464958],
        [0.95163331, 0.96485331, 0.96688892, 0.03128554]],

       [[0.95204256, 0.95529161, 0.96616912, 0.02464958],
        [0.95163331, 0.96485331, 0.96688892, 0.03128554],
        [0.95725128, 0.95807422, 0.95844067, 0.04589107]],

       [[0.95163331, 0.96485331, 0.96688892, 0.03128554],
        [0.95725128, 0.95807422, 0.95844067, 0.04

In [126]:
reg.compile(optimizer='adam', loss = 'mean_squared_error')



In [127]:
######SOMETHINGS MESSED UP



reg.fit(X_train, y_train, epochs=100, batch_size=16, verbose=1)

Epoch 1/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0284
Epoch 2/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 3/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 4/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0032
Epoch 5/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0028
Epoch 6/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 7/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0026
Epoch 8/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0021
Epoch 9/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0020
Epoch 10/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0021
Epoch 11/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0021
Epoch 12/100
79/79 [==============================] - 0s 2ms/step - loss: 0.0018
Epoch 13/100
79/79 [=================

# PREP DATA SET